In [13]:
import pandas as pd

In [14]:
import re

In [15]:
import statistics

In [16]:
appellate08 = pd.read_csv('C:/Users/jwang/OneDrive/Desktop/SupremeCourt/supreme_court/ap08on.txt', delimiter = "\t", dtype = str)

In [ ]:
appellate08['Cleaned_Docket'] = appellate08['DOCKET'].str[:2] + "-" + appellate08['DOCKET'].str[2:] #split the docket column into two and separated by a dash

In [17]:
appellate08.iloc[:, : 10]

,CIRCUIT,DOCKET,REOPEN,DKTDATE,USAPT,APPELLAN,USAPE,APPELLEE,APPTYPE,ORGPROC
0,0,0001434,-8,10/10/2000,0,SPECLTY ET AL,1,EPA,1,-8
1,0,0001435,-8,10/10/2000,0,AMER ET AL,1,EPA,1,-8
2,0,0203008,1,05/02/2008,0,PARTY 2,0,PARTY 1,3,-8
3,0,0203104,-8,11/18/2002,0,NaN,1,NaN,17,-8
4,0,0301072,-8,03/12/2003,0,KAY,0,FEDERAL COMMUNICATIO,1,-8
...,...,...,...,...,...,...,...,...,...,...
813640,11,2190028,-8,10/13/2021,0,LOPER,0,LIFEGUARD AMBULANCE,22,-8
813641,11,2190029,-8,10/27/2021,0,BAKER,0,STATE FARM MUTUAL AU,22,-8
813642,11,2190030,-8,10/18/2021,0,JAYE,0,UNITED STATES OF AME,22,-8
813643,11,2190031,-8,12/01/2021,0,ZURICH AMERICAN INSU,0,HARDIN,22,-8
813644,11,2190032,-8,12/20/2021,0,TOYOTA MOTOR CORPORA,0,CARDENAS,22,-8

In [18]:
appellate08.iloc[:,10 : 20] #DDIST is wrong;

       AGENCY JURIS  NOS OFFENSE DCIRC DDIST DOFFICE  DDOCKET DDEFNUM FEDCAP
0           7    -9   -9      -9     0    90       1       -8      -8     -8
1           7    -9   -9      -9     0    90       1       -8      -8     -8
2          -9     2  510      -9     0    90       1  9600053      -8     -8
3          -9    -9   -9    7830     0    90       1  0100073      -8     -8
4         FCC    -9   -9      -9    -8    -8      -8       -8      -8     -8
...       ...   ...  ...     ...   ...   ...     ...      ...     ...    ...
813640     -9    -9   -9      -9    11    26       2  1900583      -8     -8
813641     -9    -9   -9      -9    11    3G       4  1900014      -8     -8
813642     -9    -9   -9      -9    11    28       1  2100310      -8     -8
813643     -9    -9   -9      -9    11    3E       1  2001594      -8     -8
813644     -9    -9   -9      -9    11    3C       1  1822798      -8     -8

[813645 rows x 10 columns]

In [ ]:
appellate08.iloc[90:100,20 : 30] #FILEFEE requires clarification;

In [ ]:
appellate08.iloc[:,30 : 40] #check through the date format

In [ ]:
appellate08.iloc[:,40 : 50] #all JDGCODE and JDGINV requires further inquiry;

In [ ]:
appellate08.iloc[:,50 : 60]

In [ ]:
 print(statistics.mean([len(i) for i in appellate08['Cleaned_Docket']])) #confirm that all string length are 8

In [ ]:
print(type(appellate08['CRECDATE']))

In [ ]:
appellate08['CRECDATE'].dtype

In [ ]:
appellate08['BRFILED'].dtype

In [ ]:
appellate08['APPELLAN'].dtype